config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'total_analytics#index'

  namespace :ifrs do
    namespace :comprehensive_incomes do
      resources :data_methods, except: :show
    end

    namespace :financial_positions do
      resources :data_methods, except: :show
    end
  end

  resources :companies do
    post 'parse_and_calculate', to: 'companies#parse_and_calculate', as: 'parse_and_calculate'
    post 'calculate', to: 'companies#calculate', as: 'calculate'

    namespace :ifrs do
      resources :comprehensive_incomes, only: %i[index]
      post 'parse_comprehensive_incomes', to: 'comprehensive_incomes#parse', as: 'parse_comprehensive_incomes'

      resources :financial_positions, only: %i[index]
      post 'parse_financial_positions', to: 'financial_positions#parse', as: 'parse_financial_positions'
    end

    namespace :analytics do
      resources :foundations, only: %i[index]
      post 'calculate_foundations', to: 'foundations#calculate', as: 'calculate_foundations'

      resources :ratios, only: %i[index]
      post 'calculate_ratios', to: 'ratios#calculate', as: 'calculate_ratios'

      post 'calculate_results', to: 'results#calculate', as: 'calculate_results'
    end

    resources :shares, except: %i[show]
    post 'parse_shares', to: 'shares#parse', as: 'parse_shares'
  end

  get 'total_analytics', to: 'total_analytics#index', as: 'total_analytics'
  post 'calculate_total_analytics', to: 'total_analytics#calculate', as: 'calculate_total_analytics'
end

app/models/share.rb
# frozen_string_literal: true

class Share < ApplicationRecord
  default_scope { order(date: :desc) }

  belongs_to :company
end

app/controllers/shares_controller.rb
# frozen_string_literal: true

class SharesController < ApplicationController
  before_action :find_company
  before_action :find_share, only: %i[edit update destroy]

  def index
    base_breadcrumbs

    @grid = SharesGrid.new(grid_params) do |scope|
      scope.where(company_id: @company.id).page(params[:page])
    end
  end

  def edit
    base_breadcrumbs
    breadcrumb "#{I18n.t('form.edit')} #{@share.id}", edit_company_share_path(@company.id, @share.id)
  end

  def update
    @share.update!(share_params)
    redirect_to(action: :index, company_id: @company.id)
  end

  def new
    @share = @company.shares.new

    base_breadcrumbs
    breadcrumb I18n.t('form.create'), new_company_share_path(@company.id)
  end

  def create
    share = Share.create!(share_params.merge(company_id: @company.id))
    redirect_to(action: :index, company_id: @company.id, id: share.id)
  end

  def destroy
    @share.destroy!
    redirect_to(action: :index, company_id: @company.id)
  end

  def parse
    Shares::ParserWorker.perform_async(@company.id)
    redirect_to(action: :index, company_id: @company.id)
  end

  private

  def share_params
    params.require(:share).permit(:amount, :value, :date)
  end

  def grid_params
    params.fetch(:shares_grid, {}).permit!
  end

  def find_company
    @company = Company.find(params[:company_id])
  end

  def find_share
    @share = @company.shares.find(params[:id])
  end

  def base_breadcrumbs
    breadcrumb I18n.t('companies'), companies_path
    breadcrumb @company.name, company_path(@company.id)
    breadcrumb I18n.t('shares'), company_shares_path(@company.id)
  end
end

app/views/shares/_form.html.slim
div
  = form.label :amount, I18n.t('share.amount')
  = form.text_field :amount, placeholder: 'В тыс.', required: true

div
  = form.label :value, I18n.t('share.value')
  = form.text_field :value, required: true

div
  = form.label :date, I18n.t('date')
  = form.text_field :date, placeholder: 'dd.mm.yyyy', required: true

app/views/shares/edit.html.slim
= form_for(@share, url: company_share_path(@company.id, @share.id), method: :put) do |form|
  = render(partial: 'form', locals: { form: form })
  = form.submit I18n.t('form.save')

app/views/shares/index.html.slim
= link_to(I18n.t('form.create'), new_company_share_path(@company.id))
br
= link_to(I18n.t('parse'), company_parse_shares_path(@company.id), method: :post)

= paginate(@grid.assets)
= datagrid_table @grid
= paginate(@grid.assets)

app/views/shares/new.html.slim
= form_for(@share, url: company_shares_path(@company.id)) do |form|
  = render(partial: 'form', locals: { form: form })
  = form.submit I18n.t('form.create')