config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'total_analytics#index'

  namespace :ifrs do
    namespace :comprehensive_incomes do
      resources :data_methods, except: :show
    end

    namespace :financial_positions do
      resources :data_methods, except: :show
    end
  end

  resources :companies do
    post 'parse_and_calculate', to: 'companies#parse_and_calculate', as: 'parse_and_calculate'
    post 'calculate', to: 'companies#calculate', as: 'calculate'

    namespace :ifrs do
      resources :comprehensive_incomes, only: %i[index]
      post 'parse_comprehensive_incomes', to: 'comprehensive_incomes#parse', as: 'parse_comprehensive_incomes'

      resources :financial_positions, only: %i[index]
      post 'parse_financial_positions', to: 'financial_positions#parse', as: 'parse_financial_positions'
    end

    namespace :analytics do
      resources :foundations, only: %i[index]
      post 'calculate_foundations', to: 'foundations#calculate', as: 'calculate_foundations'

      resources :ratios, only: %i[index]
      post 'calculate_ratios', to: 'ratios#calculate', as: 'calculate_ratios'

      post 'calculate_results', to: 'results#calculate', as: 'calculate_results'
    end

    resources :shares, except: %i[show]
    post 'parse_shares', to: 'shares#parse', as: 'parse_shares'
  end

  get 'total_analytics', to: 'total_analytics#index', as: 'total_analytics'
  post 'calculate_total_analytics', to: 'total_analytics#calculate', as: 'calculate_total_analytics'
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  belongs_to :country
  belongs_to :industry
  belongs_to :finam_em, class_name: 'Finam::Em'

  has_many :ifrs_financial_positions, class_name: 'Ifrs::FinancialPosition'
  has_many :ifrs_comprehensive_incomes, class_name: 'Ifrs::ComprehensiveIncome'
  has_many :shares
  has_many :analytics_foundations, class_name: 'Analytics::Foundation'
  has_many :analytics_ratios, class_name: 'Analytics::Ratio'
  has_many :analytics_results, class_name: 'Analytics::Result'

  scope :with_analytics, -> { joins(:analytics_foundations, :analytics_ratios) }

  validates :name, presence: true, uniqueness: true
  validates :index, presence: true, uniqueness: true

  def ready_for_analytics_calculation?
    conomy_url.present? &&
      ifrs_financial_positions.present? &&
      ifrs_comprehensive_incomes.present? &&
      shares.present?
  end

  def perform_calculating
    return unless ready_for_analytics_calculation?

    Analytics::CalculateAllWorker.perform_async(id)
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  breadcrumb I18n.t('companies'), :companies_path

  before_action :find_company, only: %i[show edit update destroy parse_and_calculate calculate]
  before_action :perform_select_options, only: %i[new edit create update]

  def index
    @grid = CompaniesGrid.new(grid_params) do |scope|
      scope.page(params[:page])
    end
  end

  def new
    @company = Company.new

    breadcrumb I18n.t('form.create'), new_company_path
  end

  def show
    breadcrumb @company.name, company_path(@company.id)
  end

  def create
    @company = Company.new(company_params)
    @company.save!
    Companies::SetConomyUrlWorker.perform_async(@company.id)
    redirect_to(action: :show, id: @company.id)
  rescue ActiveRecord::RecordInvalid
    render(:new)
  end

  def edit
    breadcrumb "#{I18n.t('form.edit')} #{@company.name}", edit_company_path(@company.id)
  end

  def update
    @company.update!(company_params)
    redirect_to(action: :show, id: @company.id)
  rescue ActiveRecord::RecordInvalid
    render(:edit)
  end

  def destroy
    @company.destroy!
    redirect_to(action: :index)
  end

  def parse_and_calculate
    Ifrs::ComprehensiveIncomes::ParserWorker.perform_async(@company.id, true)
    Ifrs::FinancialPositions::ParserWorker.perform_async(@company.id, true)
    Shares::ParserWorker.perform_in(1.minute, @company.id, true)

    redirect_to(action: :show, id: @company.id)
  end

  def calculate
    Analytics::CalculateAllService.call(@company)

    redirect_to(action: :show, id: @company.id)
  end

  private

  def grid_params
    params.fetch(:companies_grid, {}).permit!
  end

  def find_company
    @company = Company.find(params[:id] || params[:company_id])
  end

  def company_params
    params.require(:company)
          .permit(:name, :index, :country_id, :industry_id, :finam_em_id)
          .reject { |_key, value| value.blank? }
  end

  def perform_select_options
    @countries = Country.select_options
    @industries = Industry.select_options
    @finam_ems = Finam::Em.select_options
  end
end

app/views/companies/_form.html.slim
div
  = form.label :name, I18n.t('company.name')
  = form.text_field :name, required: true

div
  = form.label :index, I18n.t('company.index')
  = form.text_field :index, required: true

div
  = form.label :country_id, I18n.t('country.name')
  = form.select :country_id, @countries, required: true, include_blank: true

div
  = form.label :industry_id, I18n.t('industry.name')
  = form.select :industry_id, @industries, required: true, include_blank: true

div
  = form.label :finam_em, I18n.t('company.finam_em')
  = form.select :finam_em_id, @finam_ems, required: true, include_blank: true

- if @company.errors.present?
  div
    - @company.errors.full_messages.each do |error|
      p = error

app/views/companies/edit.html.slim
= form_for(@company, url: company_path(@company.id), method: :put) do |form|
  = render(partial: 'form', locals: { form: form })
  = form.submit I18n.t('form.save')

app/views/companies/index.html.slim
= link_to(I18n.t('form.create'), new_company_path)

= datagrid_form_for @grid, :method => :get, :url => companies_path

= paginate(@grid.assets)
= datagrid_table @grid
= paginate(@grid.assets)

app/views/companies/new.html.slim
= form_for(@company, url: companies_path) do |form|
  = render(partial: 'form', locals: { form: form })
  = form.submit I18n.t('form.create')

app/views/companies/show.html.slim
div
  a = "ID: #{@company.name}"
div
  a = "#{I18n.t('company.name')}: #{@company.name}"
div
  a = "#{I18n.t('company.index')}: #{@company.index}"
div
  a = "#{I18n.t('company.country')}: #{@company.country.name}"
div
  a = "#{I18n.t('company.industry')}: #{@company.industry.name}"
div
  a = "#{I18n.t('company.finam_em_name')}: #{@company.finam_em&.name}"
div
  a = "#{I18n.t('company.conomy_url')}: "
  = @company.conomy_url.nil? ? '' : link_to(@company.conomy_url, @company.conomy_url, target: '_blank')
- if @company.conomy_url.present?
  div
    = link_to(I18n.t('parse_and_calculate'), company_parse_and_calculate_path(@company.id), method: :post)
  div
    = link_to(I18n.t('calculate_all_analytics'), company_calculate_path(@company.id), method: :post)
div
  = link_to(I18n.t('ifrs_comprehensive_incomes'), company_ifrs_comprehensive_incomes_path(@company.id))
div
  = link_to(I18n.t('ifrs_financial_positions'), company_ifrs_financial_positions_path(@company.id))
div
  = link_to(I18n.t('shares'), company_shares_path(@company.id))
div
  = link_to(I18n.t('analytics_foundations'), company_analytics_foundations_path(@company.id))
div
  = link_to(I18n.t('analytics_ratios'), company_analytics_ratios_path(@company.id))
div
  = link_to(I18n.t('analytics_results_calculate'), company_analytics_calculate_results_path(@company.id), method: :post)