config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'total_analytics#index'

  namespace :ifrs do
    namespace :comprehensive_incomes do
      resources :data_methods, except: :show
    end

    namespace :financial_positions do
      resources :data_methods, except: :show
    end
  end

  resources :companies do
    post 'parse_and_calculate', to: 'companies#parse_and_calculate', as: 'parse_and_calculate'
    post 'calculate', to: 'companies#calculate', as: 'calculate'

    namespace :ifrs do
      resources :comprehensive_incomes, only: %i[index]
      post 'parse_comprehensive_incomes', to: 'comprehensive_incomes#parse', as: 'parse_comprehensive_incomes'

      resources :financial_positions, only: %i[index]
      post 'parse_financial_positions', to: 'financial_positions#parse', as: 'parse_financial_positions'
    end

    namespace :analytics do
      resources :foundations, only: %i[index]
      post 'calculate_foundations', to: 'foundations#calculate', as: 'calculate_foundations'

      resources :ratios, only: %i[index]
      post 'calculate_ratios', to: 'ratios#calculate', as: 'calculate_ratios'

      post 'calculate_results', to: 'results#calculate', as: 'calculate_results'
    end

    resources :shares, except: %i[show]
    post 'parse_shares', to: 'shares#parse', as: 'parse_shares'
  end

  get 'total_analytics', to: 'total_analytics#index', as: 'total_analytics'
  post 'calculate_total_analytics', to: 'total_analytics#calculate', as: 'calculate_total_analytics'
end

app/controllers/total_analytics_controller.rb
# frozen_string_literal: true

class TotalAnalyticsController < ApplicationController
  breadcrumb I18n.t('total_analytics_name'), :total_analytics_path

  before_action :perform_select_options, only: %i[index]
  before_action :perform_input_values, only: %i[index]

  # rubocop:disable Metrics/MethodLength
  def index
    @keys = Analytics::Results::CalculateService::ATTRS
    @companies_names = companies.each_with_object({}) do |company, result|
      result[company.id.to_s] = company.name
    end
    @companies_analytics = (start_year..end_year).map do |year|
      {
        year: year,
        analytics: companies.each_with_object({}) do |company, result|
          result[company.id.to_s] = company.analytics_results.find { |ar| ar.date.year == year }
        end,
      }
    end.reverse
  end
  # rubocop:enable Metrics/MethodLength

  def calculate
    Company.all.each do |company|
      Analytics::CalculateAllWorker.perform_async(company.id)
    end
    redirect_to(action: :index)
  end

  private

  def companies
    @companies ||= Company.with_analytics.where({
      country_id: @country_id,
      industry_id: @industry_id,
    }.select { |_key, value| value.present? })
  end

  def start_year
    @start_year ||= begin
      index_params[:start_date].present? ? Date.parse(index_params[:start_date]).year : Share.minimum(:date).year
    end
  end

  def end_year
    @end_year ||= begin
      index_params[:end_date].present? ? Date.parse(index_params[:end_date]).year : Share.maximum(:date).year
    end
  end

  def index_params
    @index_params ||= params.permit(:country_id, :industry_id, :start_date, :end_date)
  end

  def perform_input_values
    @country_id = index_params[:country_id] || Country.first.id
    @industry_id = index_params[:industry_id] || Industry.first.id
  end

  def perform_select_options
    @countries = Country.select_options
    @industries = Industry.select_options
    @dates = begin
               (Share.minimum(:date).year..Share.maximum(:date).year).map do |year|
                 ["31.12.#{year}", "31.12.#{year}"]
               end
             rescue NoMethodError
               ['', '']
             end
  end
end

app/views/total_analytics/_filter_form.html.slim
= form_with(url: total_analytics_path, method: 'get') do
  div
    = label_tag(:country_id, I18n.t('country.name'))
    = select_tag(:country_id, options_for_select(@countries, selected: @country_id), include_blank: true)
  div
    = label_tag(:industry_id, I18n.t('industry.name'))
    = select_tag(:industry_id, options_for_select(@industries, selected: @industry_id), include_blank: true)
  div
    = label_tag(:start_date, I18n.t('start_date'))
    = select_tag(:start_date, options_for_select(@dates, selected: "31.12.#{@start_year}"))
  div
    = label_tag(:end_date, I18n.t('end_date'))
    = select_tag(:end_date, options_for_select(@dates, selected: "31.12.#{@end_year}"))
  div
    = submit_tag(I18n.t('find'))

app/views/total_analytics/_table.html.slim
table
  thead
    tr
      th = year
      - analytics.keys.each do |company_id|
        th = link_to(@companies_names[company_id], company_path(company_id), target: '_blank')
  tbody
    - @keys.each do |key|
      tr
        td.width-min-400 = I18n.t("total_analytics.#{key}")
        - analytics.values.each do |analytics|
          - if analytics.nil? || analytics[key].nil?
            td.width-min-75 = '-'
          - else
            td.width-min-75 class=Analytics::Results::StyleBuilderService.call(key, analytics[key]) = analytics[key]

app/views/total_analytics/_tables.html.slim
- @companies_analytics.each do |company_analytics|
  div
    = render(partial: 'table', locals: { year: company_analytics[:year], analytics: company_analytics[:analytics] })

app/views/total_analytics/index.html.slim
= link_to(I18n.t('calculate_for_all_companies'), calculate_total_analytics_path, method: :post)

= render(partial: 'filter_form')
div id="tables"
  = render(partial: 'tables')

app/views/total_analytics/index.js.erb
$("#tables").html("<%= j render(partial: 'tables') %>")